/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package a11yongnomen;

import java.net.URL;;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            String classNAme = "org.GNOME.Accessibility.AtkWrapper";
            Class<?> gnomeAtkWrapper = Class.forName(classNAme);
            if (gnomeAtkWrapper != null) {
                System.out.println("Class " + classNAme + " has louded");
                ClassLoader loader = gnomeAtkWrapper.getClassLoader();
                if (loader != null) {
                    System.out.println(loader.getResource("foo/" + classNAme + ".class"));
                } else {
    // Try the bootstrap classloader - obtained from the ultimate parent of the System Class Loader.
    loader = ClassLoader.getSystemClassLoader();
    while ( loader != null && loader.getParent() != null ) {
      loader = loader.getParent();
    }
  }
  if (loader != null) {
    String name = gnomeAtkWrapper.getCanonicalName();
    URL resource = loader.getResource(name.replace(".", "/") + ".class");
    if ( resource != null ) {
      System.out.println(resource.toString());
                }
            }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(new App().getGreeting());
    }
}
